# rustfmt.toml
# use_small_heuristics = "Max"
style_edition = "2024"
group_imports = "StdExternalCrate"
unstable_features = true
comment_width = 100
format_code_in_doc_comments = true
imports_granularity = "Crate"
imports_layout = "Vertical"
wrap_comments = true